#!/usr/bin/env  zsh

# NOT FINISHED!!!
#-----------------------------------------------------------------------------------
# This script is to install turtlebot 3 from source
#
# Author: Hao Feng (F1)
# Date:   Dec. 21, 2021
#
# Copyright (c) 2021, FATAVAY CO., LTD.
#-----------------------------------------------------------------------------------

export os=`uname`
export home=/Users/fengh
export distribution_default=foxy
export run_default=install
export shell_dir=$(cd "$(dirname "$0")";pwd)
export compiler_default=clang

#-----------------------------------------------------------------------------------
function print_welcome {
    echo
    echo "* ----------------------------------------------------------------- "
    echo "* This script is to install TURTLEBOT 3 from source ... "

    echo
    echo "* ------- "
    echo "* specify ros distribution name ... "
    echo
    echo  "         ROS1: melodic/noetic "
    echo  "         ROS2: foxy/galactic/rolling "
    echo
    echo -n " * Please input ros name, [$distribution_default]: "
    read distribution
    if [[ $distribution == "" ]]; then export distribution=$distribution_default; fi

    echo
    echo "* ------- "
    echo "* specify run mode ... "
    echo
    echo -n "* Please input run mode: install/remove, [$run_default]: "
    read run
    if [[ $run == "" ]]; then export run=$run_default; fi

    echo
    echo "* ------- "
    echo "* specify compilers ... "
    echo
    echo -n "* Please input compilers: clang/gnu/intel, [$compiler_default]: "
    read compiler
    if [[ $compiler == "" ]]; then export compiler=$compiler_default; fi

    catkin_default=$home/Research/ROS/turtlebot3
    echo
    echo "* ------- "
    echo "* specify ros working directory ... "
    echo
    echo -n "* Please input the working turblebot 3 directory, [$catkin_default]: "
    read catkin
    if [[ $catkin == "" ]]; then export catkin=$catkin_default; fi
    export bipath=/opt/ros/turtlebot3_src
    echo "The build & install base is: $bipath"
    echo
}

#-----------------------------------------------------------------------------------
function set_compiler {
        case $compiler in
        gnu)
            export CC=gcc-11
            export CXX=g++-11
            ;;
        intel)
            export CC=icc
            export CXX=icpc
            ;;
        clang)
            export CC=clang
            export CXX=clang++
            ;;
    esac

    echo
    echo "* ------ "
    echo "* compilers are: "
    echo "     - C compiler:        $CC"
    echo "     - CXX compiler:      $CXX"
    echo
}

#-----------------------------------------------------------------------------------
function set_gazebo {
    echo
    echo "* ------ "
    echo "* brew/apt $run gazebo ... "
    echo
    
    case $os in
        Darwin)
            source ~/Init/brew.x86

            arch -x86_64 /usr/local/bin/brew tap osrf/simulation
            arch -x86_64 /usr/local/bin/brew $run gazebo11
            ;;
        Linux)
            for lib in ros-$distribution-gazebo-dev     \
                       ros-$distribution-gazebo-ros2-control                  \
                       ros-$distribution-gazebo-msgs    \
                       ros-$distribution-gazebo-ros2-control-dbgsym           \
	               ros-$distribution-gazebo-msgs-dbgsym \
                       ros-$distribution-gazebo-ros2-control-demos            \
	               ros-$distribution-gazebo-plugins        \
                       ros-$distribution-gazebo-ros2-control-demos-dbgsym     \
	               ros-$distribution-gazebo-plugins-dbgsym \
                       ros-$distribution-gazebo-ros-dbgsym                    \
	               ros-$distribution-gazebo-ros           \
                       ros-$distribution-gazebo-ros-pkgs 
            do
	        sudo apt-get $run -y $lib
            done
            ;;
    esac
}

#-----------------------------------------------------------------------------------
function get_code {
    echo
    echo "* ------- "
    echo
    echo "* create catkin workspace --- $catkin & ./src ..."
    mkdir -p $catkin/src && cd $catkin

    echo
    echo "* ------- "
    echo "* download ros source codes ..."
    echo

    # cp $shell_dir/turtlebot3.repos .
    # vcs import src < turtlebot3.repos

    cd src
    git clone -b ${distribution}-devel https://github.com/ROBOTIS-GIT/turtlebot3.git
    git clone -b ${distribution}-devel https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git
    git clone -b ${distribution}-devel https://github.com/ROBOTIS-GIT/turtlebot3_simulations.git
    git clone -b ${distribution}-devel https://github.com/ROBOTIS-GIT/DynamixelSDK.git
    git clone -b ${distribution}-devel https://github.com/ROBOTIS-GIT/hls_lfcd_lds_driver.git
}

#-----------------------------------------------------------------------------------
function set_env {
    if [[ $os == "Darwin" ]]; then
        source ~/Init/brew.x86
    fi

    source ~/Init/$distribution
    
    case $os in
        Darwin)
            export OPENSSL_ROOT_DIR=$(brew --prefix openssl)
            ;;
        *)
            ;;
    esac

    echo
    echo "* ------ "
    echo "* environments are: "
    echo "     - OPENSSL_ROOT_DIR:  $OPENSSL_ROOT_DIR"
    echo
}

#-----------------------------------------------------------------------------------
function build_src {
    cd $catkin

    export build_base=$bipath/build
    export install_base=$bipath/install

    comp () {
        colcon \
            --log-base /dev/null     \
            build --symlink-install  \
            --build-base $build_base \
            --install-base $install_base \
            --event-handlers console_direct+ \
            $@
    }

    comp
}

#-----------------------------------------------------------------------------------
# main function

print_welcome

get_code
set_compiler
set_env
set_gazebo
build_src
